all: expand.o factor.o
	chmod +x *
	@echo Compiled all projects

expand.o: expand.cpp
	@echo Making expand
	g++ expand.cpp -o expand

factor.o: factor.cpp
	@echo Making factor
	g++ factor.cpp -o factor
