#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'Usage: ./sfrm <arg1> <arg2> ...'
    echo
    echo 'Type "./sfrm help" to see commands'
    exit 0
fi

if [[ "$1" = "help" ]] ; then
    echo 'This tool safely romves files for you and places them in ~/.trash.  You can use the "unsfrm" tool to take your items out of the trash.'
    echo 'sfrm works only with ordinary files (i.e., not directories, symbolic links, etc.)'
fi

# Loop over for however many arguments
# existing file doesn't work
for var in "$@"
do
  #strip off directory before file name
  basename=`basename $var`
  # Make sure it is a regular file
  if [ -f $var ]; then
    if [ -f ~/.trash/$basename ]; then
      # Ensure user choses new name
      while : ; do
        echo "Cannot move $var. $basename already exists in trash."
        read -p "New name to store under: " name
        # User input is not equal to anything else in trash
	if [ ! -f ~/.trash/$name ]; then
		basename=$name
		mv $var ~/.trash/$basename
		echo "safely reomved $var to the trash as $basename"
		break
	fi
	echo "Try again. $name also exsists in trash"
	echo 
      done

    # Doesn't exist in trash safe to move in
    else
      mv $var ~/.trash/$basename
      echo "Safely removed $var to the trash"  
  fi
  else
    echo "Sorry this is not a regular file or doesn't exist.  Can't move to trash"
  fi
done
